name: Deploy to server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      # 部署推送
      - name: Rsync
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          ARGS: "-avz"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.BACKEND_DIR }}
          
      - name: Run SSH command
        uses: appleboy/ssh-action@v0.1.4
        with:
          script: |
            cd ${{ secrets.BACKEND_DIR }}  
            pipenv install                 
            pipenv run python3 manage.py migrate      
            uwsgi --reload ~/fduhole/conf/uwsgi.pid
          host: ${{ secrets.REMOTE_HOST }}
          username: 'shi'
          key: ${{ secrets.ACCESS_TOKEN }}
#           password: ${{ secrets.SERVER_PASSWORD }}
